### PR TITLE
Add default url for BASE_URL

### PR DESCRIPTION
**Pull request by mellson**
If the BASE_URL is not set use an empty string.

### CODE REVIEW

**Comment by rwieruch** [comment]
I would make it required to define a BASE_URL. It's fine to just have it `http://localhost:3000` in *.env* file. Maybe worth to add this to the installation instructions of the README.md instead as a Pull Request. Something like: put `BASE_URL=http://localhost:3000` in *.env*

**Comment by mellson** [comment]
Thanks for a quick reply.
I thought about just adding the info to the README, but maybe it's a bit much to require a .env file and a BASE_URL?
And I saw that you already did it this way in other places so I thought it would make for a sensible default.
But if you disagree I can move it to the README, no problem 😊

**Comment by rwieruch** [comment]
TBH I am not sure whether the empty string works for client **and** server-side Apollo Client requests. If I remember correctly, I had to set an absolute path here to make it work for both.

**Comment by mellson** [comment]
I added a new section to the README. But maybe it would be best to leave in the blank default, that way it will work in local development even if the user forgets to set the BASE_URL.

**Comment by rwieruch** [comment]
Hm. thought about this again and I wouldn't want to give a sensible default here. The installation instructions of the project should give everything that's needed to run the project in dev or prod. There shouldn't be surprises for production. The additions to the README.md are good though!

**Comment by rwieruch** [comment]
Tried the sensible default again and ran into 

Screenshot 2020-01-24 at 00 01 47

So let's keep it without the default :-)

**Comment by mellson** [comment]
I've removed the empty string as a default again. Makes sense to require the BASE_URL since it's needed 😊

**Comment by rwieruch** [comment]
Looks good now! Thanks for your help and discussion 🎉 👍

**Pull request merged**
